// Place any global data in this file.
// You can import this data from anywhere in your site by using the `import` keyword.

export const SITE_TITLE = '30 Day Map Challenge 2023'
export const SITE_DESCRIPTION = 'Welcome to my website!'

export const MAPBOX_ACCESS_TOKEN =
  'pk.eyJ1IjoieWFuby1oIiwiYSI6ImNsb2Z6YTFhajAzZ2Uyd3Brc3BiOXlhaHgifQ.v1wFw2cWChC0dVvF63A83A'

export const AWS_LOCATIONSERVICE_APIKEY =
  'v1.public.eyJqdGkiOiIyNDg1NDVhMi05YmE1LTRhNDgtYjRiMC1mOTE5NDU0NWViODYifaxbKAPbqsNmvLHiTfbKS_deE4bmKO7K_cZJYT6TRIw_Pn7ijG7i-lKIz4kFmZsaTWWWG4axhS0OZ7Zh1YSWFzlhjt1NeoQNgHl_wS4u5LKhIOzJD1cDRlG-c5ptLitkeQ_j5G3RZxWw2pVObaGnhldTqowIHRVZzobFItbVCriVEhiswNrULQ9HpmI4nFAWIrsTUAgLor_yAH8lJGuFFFeDGSD9S4jViBDc3fu_lpuv5ldvFxTQi9C8-9r5mzqO7cJ_r_-B1DqqbjOw6Og35JXg5kBZlXxCVjeTv3OXjg76QiEJp7XD1QvLWHp7PxVZDtkeGtOJrAT5MNDUpMT3eoc.YTAwN2QzYTQtMjA4OC00M2Q5LWE5ZTUtYjk4Y2U1YWUxY2Uy'

export const CESIUM_ION_ACCESS_TOKEN =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJiYzY0NTlhNS1kZDI5LTQxNDItYjhmNy0wYjBjNTNmNzJjMTAiLCJpZCI6MTc5MzA2LCJpYXQiOjE3MDAzNjE1NjJ9.5s4qMal1TBlJSpb5fgDyqQakQe9Au26DZEHhNvyFXhg'

export const MAPTILER_API_KEY = 'mukxy7lulVqSPF706DLU'
